// Code generated by jtd-codegen for Rust v0.2.1

use chrono::{DateTime, FixedOffset};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AccessControl {
    #[serde(rename = "example.access-control.access.assign")]
    ExampleAccessControlAccessAssign(AccessControlExampleAccessControlAccessAssign),

    #[serde(rename = "example.access-control.access.revoke")]
    ExampleAccessControlAccessRevoke(AccessControlExampleAccessControlAccessRevoke),
}

#[derive(Serialize, Deserialize)]
pub enum AccessControlExampleAccessControlAccessAssignDataRole {
    #[serde(rename = "OWNER")]
    Owner,

    #[serde(rename = "READER")]
    Reader,
}

#[derive(Serialize, Deserialize)]
pub struct AccessControlExampleAccessControlAccessAssignData {
    #[serde(rename = "id")]
    pub id: String,

    #[serde(rename = "role")]
    pub role: AccessControlExampleAccessControlAccessAssignDataRole,

    #[serde(rename = "userId")]
    pub userId: String,

    #[serde(rename = "expiresAt")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiresAt: Option<Box<DateTime<FixedOffset>>>,
}

#[derive(Serialize, Deserialize)]
pub struct AccessControlExampleAccessControlAccessAssign {
    #[serde(rename = "data")]
    pub data: AccessControlExampleAccessControlAccessAssignData,

    #[serde(rename = "data_base64")]
    pub dataBase64: String,

    #[serde(rename = "datacontenttype")]
    pub datacontenttype: String,

    #[serde(rename = "dataschema")]
    pub dataschema: String,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(rename = "source")]
    pub source: String,

    #[serde(rename = "specversion")]
    pub specversion: String,

    #[serde(rename = "subject")]
    pub subject: String,

    #[serde(rename = "time")]
    pub time: DateTime<FixedOffset>,
}

#[derive(Serialize, Deserialize)]
pub struct AccessControlExampleAccessControlAccessRevokeData {
    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Serialize, Deserialize)]
pub struct AccessControlExampleAccessControlAccessRevoke {
    #[serde(rename = "data")]
    pub data: AccessControlExampleAccessControlAccessRevokeData,

    #[serde(rename = "data_base64")]
    pub dataBase64: String,

    #[serde(rename = "datacontenttype")]
    pub datacontenttype: String,

    #[serde(rename = "dataschema")]
    pub dataschema: String,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(rename = "source")]
    pub source: String,

    #[serde(rename = "specversion")]
    pub specversion: String,

    #[serde(rename = "subject")]
    pub subject: String,

    #[serde(rename = "time")]
    pub time: DateTime<FixedOffset>,
}
